CREATE DATABASE IF NOT EXISTS `clinic` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `clinic`;

CREATE TABLE IF NOT EXISTS `medical_examinations` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `clims_id` VARCHAR(100) NOT NULL UNIQUE,
  `serial_no` VARCHAR(100) NULL,
  `attested_by_eic` VARCHAR(255) NULL,
  `exam_date` DATE NULL,
  `full_name` VARCHAR(255) NULL,
  `age_sex` VARCHAR(50) NULL,
  `aadhar_no` VARCHAR(50) NULL,
  `address` TEXT NULL,
  `mobile_no` VARCHAR(20) NULL,
  `demo_exam_date` DATE NULL,
  `contractor_agency` VARCHAR(255) NULL,
  `ntpc_eic` VARCHAR(255) NULL,
  `diabetes` VARCHAR(10) NULL,
  `hypertension` VARCHAR(10) NULL,
  `vertigo` VARCHAR(10) NULL,
  `epilepsy` VARCHAR(10) NULL,
  `height_phobia` VARCHAR(10) NULL,
  `skin_diseases` VARCHAR(10) NULL,
  `asthma` VARCHAR(10) NULL,
  `alcohol_intake` VARCHAR(10) NULL,
  `mental_illness` VARCHAR(10) NULL,
  `tobacco_chewing` VARCHAR(10) NULL,
  `cancer` VARCHAR(10) NULL,
  `piles` VARCHAR(10) NULL,
  `hearing_problem` VARCHAR(10) NULL,
  `chronic_illness` VARCHAR(10) NULL,
  `deformity` VARCHAR(10) NULL,
  `past_accident` VARCHAR(10) NULL,
  `smoking` VARCHAR(10) NULL,
  `medicine_history` TEXT NULL,
  `contractor_signature` VARCHAR(255) NULL,
  `height` DECIMAL(10,2) NULL,
  `weight` DECIMAL(10,2) NULL,
  `bp` VARCHAR(50) NULL,
  `bmi` VARCHAR(20) NULL,
  `chest_insp` VARCHAR(50) NULL,
  `chest_exp` VARCHAR(50) NULL,
  `pulse_spo2_temp` VARCHAR(100) NULL,
  `pallor` VARCHAR(20) NULL,
  `icterus` VARCHAR(20) NULL,
  `clubbing` VARCHAR(20) NULL,
  `built` VARCHAR(20) NULL,
  `tongue` VARCHAR(100) NULL,
  `teeth` VARCHAR(100) NULL,
  `other_finding` TEXT NULL,
  `cardio_system` TEXT NULL,
  `respiratory_system` TEXT NULL,
  `cns` TEXT NULL,
  `system_other` TEXT NULL,
  `distant_r_with` VARCHAR(20) NULL,
  `distant_r_without` VARCHAR(20) NULL,
  `distant_l_with` VARCHAR(20) NULL,
  `distant_l_without` VARCHAR(20) NULL,
  `near_r_with` VARCHAR(20) NULL,
  `near_r_without` VARCHAR(20) NULL,
  `near_l_with` VARCHAR(20) NULL,
  `near_l_without` VARCHAR(20) NULL,
  `colour_vision` VARCHAR(100) NULL,
  `eye_disorder` TEXT NULL,
  `lmp` VARCHAR(50) NULL,
  `menstrual_cycle` VARCHAR(50) NULL,
  `pregnancy_duration` VARCHAR(50) NULL,
  `cbc` VARCHAR(255) NULL,
  `random_blood_sugar` VARCHAR(50) NULL,
  `urine_rm` VARCHAR(255) NULL,
  `blood_group` VARCHAR(10) NULL,
  `lft_kft` VARCHAR(255) NULL,
  `ecg` VARCHAR(20) NULL,
  `chest_xray` VARCHAR(20) NULL,
  `height_pass_test` VARCHAR(20) NULL,
  `other_tests` TEXT NULL,
  `opinion` VARCHAR(100) NULL,
  `remarks` TEXT NULL,
  `worker_signature` VARCHAR(255) NULL,
  `doctor_signature` VARCHAR(255) NULL,
  `worker_photo` VARCHAR(500) NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `data_status` ENUM('draft', 'completed', 'verified') DEFAULT 'draft'
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `form26` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `examination_id` INT NOT NULL,
  `serial_number` VARCHAR(100) NULL,
  `patient_name` VARCHAR(255) NULL,
  `father_name` VARCHAR(255) NULL,
  `address` TEXT NULL,
  `employment_details` VARCHAR(255) NULL,
  `designation` VARCHAR(255) NULL,
  `age` INT NULL,
  `fitness_status` VARCHAR(50) NULL,
  `further_exam_period` VARCHAR(255) NULL,
  `previous_certificate_no` VARCHAR(100) NULL,
  `surgeon_signature` VARCHAR(255) NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_form26_exam` FOREIGN KEY (`examination_id`) REFERENCES `medical_examinations` (`id`) ON DELETE CASCADE,
  UNIQUE KEY `uq_form26_exam` (`examination_id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `form27` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `examination_id` INT NOT NULL,
  `serial_number` VARCHAR(100) NULL,
  `department` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `sex` VARCHAR(20) NULL,
  `age` INT NULL,
  `start_date` DATE NULL,
  `leave_transfer` TEXT NULL,
  `occupation` VARCHAR(255) NULL,
  `raw_materials` TEXT NULL,
  `exam_date` DATE NULL,
  `result` VARCHAR(50) NULL,
  `signs_symptoms` TEXT NULL,
  `tests_result` TEXT NULL,
  `suspension_details` TEXT NULL,
  `certificate_issued` VARCHAR(255) NULL,
  `recertified_date` DATE NULL,
  `surgeon_signature` VARCHAR(255) NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_form27_exam` FOREIGN KEY (`examination_id`) REFERENCES `medical_examinations` (`id`) ON DELETE CASCADE,
  UNIQUE KEY `uq_form27_exam` (`examination_id`)
) ENGINE=InnoDB;
